Fixed didn't update fluid width when table was mounted
rsuite/rsuite-table pull request #433
Opened 2023-05-07 15:45 UTC by fallenleavesguy

Fixed didn't update fluid width when table was mounted

2023-05-07 15:48 UTC, fallenleavesguy commented
新的应该可以了

2023-05-08 03:04 UTC, simonguo commented
@fallenleavesguy 你可以通过以下几种方式，安装当前 PR 的 rsuite-table，看看是否修复你业务中遇到的问题？

```
# yarn 1
yarn add https://pkg.csb.dev/rsuite/rsuite-table/commit/8ce09c80/rsuite-table
# yarn 2, 3
yarn add rsuite-table@https://pkg.csb.dev/rsuite/rsuite-table/commit/8ce09c80/rsuite-table/_pkg.tgz
# npm
npm i https://pkg.csb.dev/rsuite/rsuite-table/commit/8ce09c80/rsuite-table
```

2023-05-08 03:23 UTC, fallenleavesguy commented
@simonguo 我是直接依赖的rsuite，没办法直接切换到rsuite-table

2023-05-08 06:06 UTC, simonguo commented on src/utils/useCellDescriptor.ts
> +
表格的 width 计算是在 useTableDimension 的 useMount 中完成的，按理这里 clearCache 是清除单元格配置信息，怎么能解决你当前遇到的问题，我很好奇。
https://github.com/rsuite/rsuite-table/blob/main/src/utils/useTableDimension.ts#L252

2023-05-08 06:54 UTC, fallenleavesguy commented on src/utils/useCellDescriptor.ts
> +
@simonguo 
因为现在useDescriptor跳过了useMount，width在useTableDimension中计算完成之后, useCellDescriptor不会更新。实际是只在mount之后的update才会更新。因为原来useUpdateEffect用的clearCache，所以这里也用clearCache让他更新。

原来的效果:

https://user-images.githubusercontent.com/9261562/236754579-4fc6eb35-cad3-4d49-9f8a-210a8402a85b.mov

修改之后的效果:


https://user-images.githubusercontent.com/9261562/236754951-ebf8e221-44ae-4cab-b2aa-167444366463.mov

2023-05-08 07:56 UTC, fallenleavesguy commented
急急急，在线等😱😱😱🫣

2023-05-08 10:18 UTC, simonguo commented on src/utils/useCellDescriptor.ts
> +
在这里 `clearCache()` 上添加个注释.
```
// As the cells are cached before the table width is updated, it is necessary to clear the cache again. fix: #430
```

2023-05-08 10:41 UTC, simonguo requested changes

2023-05-08 12:12 UTC, fallenleavesguy commented on src/utils/useCellDescriptor.ts
> +
同意提交了

2023-05-09 05:30 UTC, fallenleavesguy commented
要上线了，急急急🥺😭

2023-05-09 08:51 UTC, merged