Make Cell & HeaderCell generic
rsuite/rsuite-table pull request #474
Opened 2023-11-19 12:34 UTC by lorefnon

Fixes #472

2023-11-20 02:17 UTC, simonguo commented
Hi  @lorefnon  , tests failed. 
You can execute the test case locally with the following command.

```
npm run test
// or
npm run tdd
```

2023-11-22 07:11 UTC, lorefnon commented
Hi @simonguo - I have addressed the failures.

2023-11-22 08:43 UTC, simonguo requested changes
Hi @b1rdex, `children` prop should be added to `<Table>` in readme.

https://github.com/rsuite/rsuite-table/tree/main#table

2023-11-22 08:43 UTC, simonguo commented on test/Table.test.tsx
> +
It is recommended to add a type check.

```suggestion
interface InventoryItem {
  id: string;
  name: string;
}

const table = React.createRef<TableInstance<InventoryItem, string>>();

<Table<InventoryItem, string> ref={table}>
  {({ Column, HeaderCell, Cell }) => (
    <>
      <Column>
        <HeaderCell>Name</HeaderCell>
        <Cell>{row => row.name}</Cell>
      </Column>
      <Column>
        <HeaderCell>Type</HeaderCell>
        {/** @ts-expect-error Property 'type' does not exist on type 'InventoryItem' */}
        <Cell>{row => row.type}</Cell>
      </Column>
    </>
  )}
</Table>;
```

2023-11-24 02:39 UTC, simonguo approved these changes
LGTM

2023-11-24 02:41 UTC, merged